apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: main
          image: ondrejsika/example-keda-consumer
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-kafka-bootstrap.kafka.svc:9092
            - name: KAFKA_TOPIC
              value: example
            - name: KAFKA_GROUP_ID
              value: default
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
